import { FSRSParameters, generatorParameters, checkParameters } from 'ts-fsrs';

/**
 * Settings for Queue response timer and rating inference.
 */
export interface ResponseTimingSettings {
    /** Minimum completed, non-outlier samples before using per-question median. Default: 5 */
    minSamplesPerQuestion: number;
    /** Rolling window size for question median calculation. Default: 20 */
    rollingWindowSize: number;
    /** Ratio of response time to median below which rating is inferred as Easy. Default: 0.6 */
    easyRatio: number;
    /** Ratio of response time to median above which rating is inferred as Hard. Default: 1.5 */
    hardRatio: number;
    /** Inactivity / outlier cutoff in milliseconds (e.g. 60000ms = 60s). Samples exceeding this are excluded from inference. */
    outlierCutoffMs: number;
    /** Default learner baseline duration in milliseconds when per-question samples are below minimum. Default: 10000ms (10s) */
    defaultLearnerMedianMs: number;
}

/**
 * Settings for Queue deterministic ranking.
 */
export interface QueueRankingSettings {
    /** Weight applied to each day overdue. Default: 2.0 */
    overdueWeight: number;
    /** Weight for retrievability / overdue factor (dominant primary). Default: 10.0 */
    retrievabilityWeight: number;
    /** Weight for difficulty factor (secondary tiebreaker / boost). Default: 0.5 */
    difficultyWeight: number;
    /** Share of not-yet-due cards to deterministically explore [0, 1]. Default: 0.1 */
    explorationShare: number;
    /** Whether to include mastered cards in the review queue. Default: false */
    includeMastered: boolean;
    /** Maximum questions in a refreshed session; 0 means unlimited. Default: 0 */
    sessionLimit: number;
}

/**
 * Full Queue FSRS and timing configuration model.
 */
export interface QueueFsrsSettings {
    /** Target requested retention [0.70, 0.99]. Default: 0.90 */
    requestedRetention: number;
    /** Minimum scheduling interval in days. Default: 1 */
    minimumInterval: number;
    /** Maximum scheduling interval in days. Default: 36500 */
    maximumInterval: number;
    /** Feature flag: if true, fallback to legacy familiarity-based scheduler. Default: true during evaluation. */
    legacyScheduler: boolean;
    /** Response timing configuration */
    timing: ResponseTimingSettings;
    /** Queue ranking weights and policies */
    ranking: QueueRankingSettings;
    /** Optional custom FSRS algorithm parameters (w vector, fuzz, steps). */
    fsrsParameters?: Partial<FSRSParameters>;
}

/**
 * Default standard FSRS parameters generated by ts-fsrs.
 */
export const defaultFsrsParameters: FSRSParameters = generatorParameters({
    enable_fuzz: false,
    request_retention: 0.90,
    maximum_interval: 36500
});

/**
 * Creates a clean default QueueFsrsSettings instance.
 */
export function createDefaultQueueFsrsSettings(): QueueFsrsSettings {
    return {
        requestedRetention: 0.90,
        minimumInterval: 1,
        maximumInterval: 36500,
        legacyScheduler: true,
        timing: {
            minSamplesPerQuestion: 5,
            rollingWindowSize: 20,
            easyRatio: 0.6,
            hardRatio: 1.5,
            outlierCutoffMs: 60000,
            defaultLearnerMedianMs: 10000
        },
        ranking: {
            overdueWeight: 2.0,
            retrievabilityWeight: 10.0,
            difficultyWeight: 0.5,
            explorationShare: 0.1,
            includeMastered: false,
            sessionLimit: 0
        },
        fsrsParameters: {
            enable_fuzz: false,
            request_retention: 0.90,
            maximum_interval: 36500
        }
    };
}

/**
 * Validates a custom FSRS parameter vector (w array of 19 or 21 numbers).
 * Returns { valid: true, parameters } or { valid: false, error: string }.
 */
export function validateFsrsParameters(w: number[]): { valid: boolean; error?: string; parameters?: number[] } {
    if (!Array.isArray(w) || (w.length !== 19 && w.length !== 21)) {
        return {
            valid: false,
            error: `FSRS parameters vector w must contain 19 or 21 numbers, got ${Array.isArray(w) ? w.length : typeof w}`
        };
    }

    try {
        const checked = checkParameters(w);
        return {
            valid: true,
            parameters: Array.from(checked)
        };
    } catch (err) {
        return {
            valid: false,
            error: err instanceof Error ? err.message : String(err)
        };
    }
}
